'use client'

import { motion } from 'framer-motion'
import {
  PenTool,
  Code2,
  ShieldCheck,
  Eye,
  Rocket,
  Pencil,
} from 'lucide-react'

const timeline = [
  {
    week: 'Week 1–2',
    label: 'Product Discovery + Design',
    description: 'Wireframes, UI mockups, brand alignment',
    icon: PenTool,
  },
  {
    week: 'Week 3–4',
    label: 'MVP Build - Core Flows',
    description: 'Core features built out with backend + UI',
    icon: Code2,
  },
  {
    week: 'Week 5',
    label: 'Auth + Admin Tools',
    description: 'Login, roles, dashboards, and basic permissions for you and your users.',
    icon: ShieldCheck,
  },
  {
    week: 'Week 6',
    label: 'Polish + Visual QA',
    description: 'Refining UI, motion, animations, and adding empty states and loading UX.',
    icon: Eye,
  },
  {
    week: 'Week 7',
    label: 'Internal Review + Feedback',
    description: 'You explore the MVP and request final changes before go-live.',
    icon: Pencil,
  },
  {
    week: 'Week 8',
    label: 'Launch + Handoff',
    description: 'We ship your MVP and hand over docs, deploy access, and training videos.',
    icon: Rocket,
  },
]

export default function AutoGeneratedTimeline({
  onNext,
  onBack,
}: {
  onNext: () => void
  onBack: () => void
}) {
  return (
    <div className="text-center">
      <h2 className="text-xl font-bold mb-2">Your 8-Week Roadmap</h2>
      <p className="text-gray-300 mb-4">
        Here’s a preview of your build timeline based on what you selected.
      </p>

      <div className="space-y-2 max-w-xl mx-auto text-left">
        {timeline.map((item, index) => {
          const Icon = item.icon
          return (
            <motion.div
              key={item.week}
              className="relative border-l-4 border-white pl-6 py-5 px-2 bg-white/5 rounded-md shadow-md"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.15 }}
            >
              <div className="absolute -left-8 top-6">
                <Icon className="w-5 h-5 text-white" />
              </div>
              <h3 className="font-semibold text-white">
                {item.week} – {item.label}
              </h3>
              <p className="text-gray-200 text-sm">{item.description}</p>
            </motion.div>
          )
        })}
      </div>

      <div className="mt-10 flex justify-between max-w-xl mx-auto">
        <button
          onClick={onBack}
          className="text-sm text-blue-500 hover:underline"
        >
          ← Back
        </button>

        <button
          onClick={onNext}
          className="bg-white/80 backdrop-blur-md text-[var(--accent)] px-5 py-2 rounded-lg text-lg font-semibold hover:drop-shadow-lg hover:scale-105 cursor-pointer transition-all ease-in-out duration-300"
        >
          Send This to Me →
        </button>
      </div>
    </div>
  )
}
