'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'

import StartPrompt from './FounderRoadmapBuilder/StartPrompt'
import SelectProductType from './FounderRoadmapBuilder/SelectProductType'
import DragFeaturePicker from './FounderRoadmapBuilder/DragFeaturePicker'
import AutoGeneratedTimeline from './FounderRoadmapBuilder/AutoGeneratedTimeline'
import EmailCaptureForm from './FounderRoadmapBuilder/EmailCaptureForm'
import ReviewSummary from './FounderRoadmapBuilder/ReviewSummary'

const stepTitles = [
  'Get Started',
  'Choose Product Type',
  'Select Key Features',
  'View Timeline',
  'Review Summary',
  'Save & Share',
]

export default function FounderRoadmapBuilder() {
  const [step, setStep] = useState(0)
  const [productType, setProductType] = useState('')
  const [features, setFeatures] = useState<string[]>([])

  const totalSteps = stepTitles.length
  const progress = ((step + 1) / totalSteps) * 100

  const next = () => setStep((prev) => Math.min(prev + 1, totalSteps - 1))
  const back = () => setStep((prev) => Math.max(prev - 1, 0))

  return (
    <section className="relative h-[90svh] w-11/12 sm:w-4/5 md:w-3/5 mx-auto flex items-center justify-center rounded-xl shadow-2xl bg-[var(--accent)] px-6 sm:px-10 text-white overflow-hidden">
      
      {/* Progress Bar */}
      <motion.div
        className="absolute top-0 left-0 h-1 bg-white/50 z-20"
        style={{ width: `${progress}%` }}
        initial={{ width: 0 }}
        animate={{ width: `${progress}%` }}
        transition={{ ease: 'easeOut', duration: 0.4 }}
      />

      {/* Step Title */}
      <div className="absolute top-4 left-1/2 -translate-x-1/2 text-sm font-medium tracking-wide text-white/70 uppercase z-10">
        {stepTitles[step]}
      </div>

      {/* Animated Content */}
      <div className="w-full max-w-2xl min-h-[540px] flex items-center justify-center">
        <AnimatePresence mode="wait" initial={false}>
          <motion.div
            key={step}
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -40 }}
            transition={{ duration: 0.4 }}
            className="w-full flex flex-col items-center justify-center text-center p-6 sm:p-10"
          >
            {step === 0 && <StartPrompt onNext={next} />}
            {step === 1 && (
              <SelectProductType
                onNext={(type: string) => {
                  setProductType(type)
                  next()
                }}
                onBack={back}
              />
            )}
            {step === 2 && (
              <DragFeaturePicker
                onNext={(selected: string[]) => {
                  setFeatures(selected)
                  next()
                }}
                onBack={back}
              />
            )}
            {step === 3 && (
              <AutoGeneratedTimeline onNext={next} onBack={back} />
            )}
            {step === 4 && (
              <ReviewSummary
                onNext={next}
                onBack={back}
                productType={productType}
                features={features}
              />
            )}
            {step === 5 && <EmailCaptureForm />}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Step Progress Dots */}
      <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex gap-3 z-10">
        {stepTitles.map((label, index) => (
          <div key={index} className="group relative">
            <motion.div
              className={`w-3 h-3 rounded-full transition-all duration-300 ${
                index === step
                  ? 'bg-white scale-125 shadow-md'
                  : 'bg-white/30'
              }`}
              animate={{
                scale: index === step ? 1.25 : 1,
                opacity: index === step ? 1 : 0.6,
              }}
              transition={{ duration: 0.3 }}
            />
            <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 scale-0 group-hover:scale-100 transition-transform bg-white text-black text-xs font-medium rounded px-2 py-1 shadow-md z-20">
              {label}
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
